# Generated by Django 3.2.7 on 2021-09-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='birthdate',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_number',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='education_level',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
